Repository marcosdosea/Feiragro, pull requests merged in 2023-09, with the labels that each got.

#118 Branch nadianne 117
  Codigo/Core/FeiragroContext.cs
  Codigo/Core/Service/ITipoProdutoService.cs
  Codigo/Core/TipoProduto.cs
  Codigo/FeiragroWeb/Controllers/TipoProdutoController.cs
  Codigo/FeiragroWeb/FeiragroWeb.csproj
  Codigo/FeiragroWeb/Mappers/TipoProdutoProfile.cs
  Codigo/FeiragroWeb/Models/TipoProdutoModel.cs
  Codigo/FeiragroWeb/Program.cs
  Codigo/FeiragroWeb/Views/Shared/_Layout.cshtml
  Codigo/FeiragroWeb/Views/TipoProduto/Create.cshtml
  Codigo/FeiragroWeb/Views/TipoProduto/Delete.cshtml
  Codigo/FeiragroWeb/Views/TipoProduto/Details.cshtml
  Codigo/FeiragroWeb/Views/TipoProduto/Edit.cshtml
  Codigo/FeiragroWeb/Views/TipoProduto/Index.cshtml
  Codigo/FeiragroWeb/appsettings.json
  Codigo/Service/TipoProdutoService.cs
Labels: enhancement

#120 Branch vere 119
  Codigo/Core/Produto.cs
  Codigo/Core/Service/IProdutoService.cs
  Codigo/FeiragroWeb/Controllers/ProdutoController.cs
  Codigo/FeiragroWeb/Controllers/TipoProdutoController.cs
  Codigo/FeiragroWeb/FeiragroWeb.csproj
  Codigo/FeiragroWeb/Mappers/ProdutoProfile.cs
  Codigo/FeiragroWeb/Models/ProdutoModel.cs
  Codigo/FeiragroWeb/Program.cs
  Codigo/FeiragroWeb/Views/Produto/Create.cshtml
  Codigo/FeiragroWeb/Views/Produto/Delete.cshtml
  Codigo/FeiragroWeb/Views/Produto/Details.cshtml
  Codigo/FeiragroWeb/Views/Produto/Edit.cshtml
  Codigo/FeiragroWeb/Views/Produto/Index.cshtml
  Codigo/Service/ProdutoService.cs
  Codigo/Service/Service.csproj
  Codigo/Service/TipoProdutoService.cs
Labels: enhancement

#128 Implementado caso de uso pessoa. #127
  Codigo/Core/Service/IPessoaService.cs
  Codigo/Core/Service/ITipoProdutoService.cs
  Codigo/FeiragroWeb/Controllers/PessoaController.cs
  Codigo/FeiragroWeb/Mappers/PessoaProfile.cs
  Codigo/FeiragroWeb/Models/PessoaModel.cs
  Codigo/FeiragroWeb/Views/Pessoa/Create.cshtml
  Codigo/FeiragroWeb/Views/Pessoa/Delete.cshtml
  Codigo/FeiragroWeb/Views/Pessoa/Details.cshtml
  Codigo/FeiragroWeb/Views/Pessoa/Edit.cshtml
  Codigo/FeiragroWeb/Views/Pessoa/Index.cshtml
  Codigo/Service/PessoaService.cs
  Codigo/Service/TipoProdutoService.cs
Labels: enhancement

#124 Criada tela para cadastro de produto. #95
  Requisitos/Prototipos/Prototipo de Alta fidelidade/Desktop/TELA_012 - ASSOCIAÇAO - CADASTRAR PRODUTO.png
Labels: documentation

#123 Criada tela PERFIL-ADICIONAR-PRODUTOR. #94
  Requisitos/Prototipos/Prototipo de Alta fidelidade/Desktop/TELA_011 - ADM - PERFIL-ADICIONAR-PRODUTOR.png
Labels: documentation

#122 Tela e modal referente a cadastrar associação. #92
  Requisitos/Prototipos/Prototipo de Alta fidelidade/Desktop/TELA_008 - ADM - CADASTRAR ASSOCIAÇAO.png
  Requisitos/Prototipos/Prototipo de Alta fidelidade/Desktop/TELA_008 - ADM - Modal cadastro.png
Labels: documentation

#121 Tela e modal referente ao Gerenciais resevas do produtor. #90
  Requisitos/Prototipos/Prototipo de Alta fidelidade/Desktop/TELA_005 - GERENCIAR RESERVAS.png
  Requisitos/Prototipos/Prototipo de Alta fidelidade/Desktop/TELA_005 - Modal reservas.png
Labels: documentation

#132 Implementação do caso de uso de Associação concluída! #130
  Codigo/Core/Service/IAssociacaoService.cs
  Codigo/FeiragroWeb/Controllers/AssociacaoController.cs
  Codigo/FeiragroWeb/Controllers/PessoaController.cs
  Codigo/FeiragroWeb/Mappers/AssociacaoProfile.cs
  Codigo/FeiragroWeb/Models/AssociacaoModel.cs
  Codigo/FeiragroWeb/Views/Associacao/Create.cshtml
  Codigo/FeiragroWeb/Views/Associacao/Delete.cshtml
  Codigo/FeiragroWeb/Views/Associacao/Details.cshtml
  Codigo/FeiragroWeb/Views/Associacao/Edit.cshtml
  Codigo/FeiragroWeb/Views/Associacao/Index.cshtml
  Codigo/Service/AssociacaoService.cs
  Codigo/Service/ProdutoService.cs
Labels: enhancement

#126 Implementar caso de uso Manter Feira
  Codigo/Core/Service/IFeiraService.cs
  Codigo/FeiragroWeb/Controllers/FeiraController.cs
  Codigo/FeiragroWeb/Mappers/FeiraProfile.cs
  Codigo/FeiragroWeb/Models/FeiraModel.cs
  Codigo/FeiragroWeb/Program.cs
  Codigo/FeiragroWeb/Views/Feira/Create.cshtml
  Codigo/FeiragroWeb/Views/Feira/Delete.cshtml
  Codigo/FeiragroWeb/Views/Feira/Details.cshtml
  Codigo/FeiragroWeb/Views/Feira/Edit.cshtml
  Codigo/FeiragroWeb/Views/Feira/Index.cshtml
  Codigo/FeiragroWeb/Views/Shared/_Layout.cshtml
  Codigo/Service/FeiraService.cs
Labels: enhancement

#134 Implementado caso de uso Ponto Associação Venda
  Codigo/Core/Service/IPontoAssociacaoService.cs
  Codigo/FeiragroWeb/Controllers/PontoAssociacaoController.cs
  Codigo/FeiragroWeb/Mappers/PontoAssociacaoProfile.cs
  Codigo/FeiragroWeb/Models/PontoAssociacaoModel.cs
  Codigo/FeiragroWeb/Program.cs
  Codigo/FeiragroWeb/Views/PontoAssociacao/Create.cshtml
  Codigo/FeiragroWeb/Views/PontoAssociacao/Delete.cshtml
  Codigo/FeiragroWeb/Views/PontoAssociacao/Edit.cshtml
  Codigo/FeiragroWeb/Views/PontoAssociacao/Index.cshtml
  Codigo/Service/PontoAssociacaoService.cs
Labels: enhancement

#136 Implementação do caso de uso Reserva. Closed #135
  Codigo/Core/Service/IReservaService.cs
  Codigo/FeiragroWeb/Controllers/ReservaController.cs
  Codigo/FeiragroWeb/Mappers/ReservaProfile.cs
  Codigo/FeiragroWeb/Models/ReservaModel.cs
  Codigo/FeiragroWeb/Properties/launchSettings.json
  Codigo/Service/ReservaService.cs
Labels: enhancement

#137 Atualizado credênciais do model
  Codigo/FeiragroWeb/Models/PontoAssociacaoModel.cs
Labels: enhancement

#149 PR #147 Alteração no banco de dados
  AnaliseProjeto/feiragro.mwb
  AnaliseProjeto/feiragro.mwb.bak
  Codigo/Core/Associacao.cs
  Codigo/Core/Feira.cs
  Codigo/Core/FeiragroContext.cs
  Codigo/Core/Pessoa.cs
  Codigo/Core/Pontoassociacao.cs
  Codigo/Core/Produto.cs
  Codigo/Core/Produtofeira.cs
  Codigo/Core/Produtovendum.cs
  Codigo/Core/Reserva.cs
  Codigo/Core/Reservaprodutofeira.cs
  Codigo/Core/Vendum.cs
  Codigo/FeiragroWeb/Controllers/AssociacaoController.cs
  Codigo/FeiragroWeb/Controllers/PessoaController.cs
  Codigo/FeiragroWeb/Models/AssociacaoModel.cs
  Codigo/FeiragroWeb/Program.cs
  Codigo/FeiragroWeb/Views/Associacao/Create.cshtml
  Codigo/FeiragroWeb/Views/Associacao/Delete.cshtml
  Codigo/FeiragroWeb/Views/Associacao/Details.cshtml
  Codigo/FeiragroWeb/Views/Associacao/Edit.cshtml
  Codigo/FeiragroWeb/Views/Associacao/Index.cshtml
  Codigo/FeiragroWeb/Views/Shared/_Layout.cshtml
  Codigo/FeiragroWeb/Views/Shared/_ValidationScriptsPartial.cshtml
  Codigo/FeiragroWeb/appsettings.json
  Codigo/Service/PessoaService.cs
Labels: enhancement

#157 Branch nadianne webtest155
  Codigo/FeiragroWebTests/Controllers/TipoProdutoControllerTests.cs
  Codigo/FeiragroWebTests/FeiragroWebTests.csproj
Labels: enhancement

#152 Adicionado prototipo de alta fidelidade TELA_007 - ADM - DASHBOARD #91
  Requisitos/Prototipos/Prototipo de Alta fidelidade/Desktop/TELA_007 - ADM - DASHBOARD.png
Labels: enhancement

#159 fix(Feira): Corrigir cadastro de feira
  Codigo/FeiragroWeb/Controllers/FeiraController.cs
  Codigo/FeiragroWeb/Models/FeiraModel.cs
  Codigo/FeiragroWeb/Views/Feira/Create.cshtml
Labels: bug

#161 Criado testes para caso de uso PontoAssociação
  Codigo/Feiragro.sln
  Codigo/FeiragroWeb/Models/PontoAssociacaoModel.cs
  Codigo/FeiragroWebTests2/Controllers/PontoAssociacaoControllerTests.cs
  Codigo/FeiragroWebTests2/FeiragroWebTests2.csproj
Labels: enhancement

#163 Implementação do ProdutoFeira
  Codigo/Core/Service/IProdutoFeiraService.cs
  Codigo/FeiragroWeb/Controllers/ProdutoFeiraController.cs
  Codigo/FeiragroWeb/Mappers/ProdutoFeiraProfile.cs
  Codigo/FeiragroWeb/Models/ProdutoFeiraModel.cs
  Codigo/Service/ProdutoFeiraService.cs
Labels: enhancement

#164 Adicionado unidade de teste para "Pessoa" e removido o projeto "WebTe…
  Codigo/Feiragro.sln
  Codigo/FeiragroWeb/Views/Shared/_Layout.cshtml
  Codigo/FeiragroWebTests/Controllers/PessoaControllerTests.cs
  Codigo/FeiragroWebTests/Controllers/PontoAssociacaoControllerTests.cs
  Codigo/FeiragroWebTests/FeiragroWebTests.csproj
  Codigo/FeiragroWebTests2/Controllers/PontoAssociacaoControllerTests.cs
  Codigo/FeiragroWebTests2/FeiragroWebTests2.csproj
Labels: enhancement
